import WireFramyBadgeAlterWithWhiteBG, {getWireFramyBadgesAlterWithWhiteBG} from "./WireFramyBadgeWhiteWithLine";

export default WireFramyBadgeAlterWithWhiteBG
export {getWireFramyBadgesAlterWithWhiteBG}